### ISSUE TITLE
Context.createDataStore removed on alpha 07

### ISSUE THREAD

**Issue by nicolasmanurung** [philipplackner/DataStoreAndroid#1]
https://developer.android.com/jetpack/androidx/releases/datastore#1.0.0-alpha07

Based on update the documentation `"The Context.createDataStore extension function has been removed and replaced with globalDataStore property delegate. Call globalDataStore once at the top level in your kotlin file"`

How to re architect the app?

**Comment by DonaldLaborde** [comment]
Hi, I have the same problem. Did you solve your problem ?

**Comment by lastCard1440** [comment]
Hi Nicolas.
I have the same problem. Did you solve it ?

**Comment by nicolasmanurung** [comment]
> 
> 
> Hi Nicolas. I have the same problem. Did you solve it ?

Ya, I have found that. It just an update and we could make
`private val Context.dataStore by preferencesDataStore("settings")`

On top our file.
Here the reference https://stackoverflow.com/a/67126676/10824243

**Comment by lastCard1440** [comment]
@nicolasmanurung thanks. 
Yes I saw the explanation here just a few moment after my question 
[(https://developer.android.com/topic/libraries/architecture/datastore) ]
